#services:
#  manage_dirs:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./database:/app/database
#    command: ["python", "app/initializer.py"]
#    networks:
#      - app-network
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#      - qdrant
#      - manage_dirs
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    networks:
#      - app-network
#
#  db:
#    image: postgres:16
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=mysecretpassword
#      - POSTGRES_DB=mydb
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - app-network
#
#  qdrant:
#    image: qdrant/qdrant:latest
#    depends_on:
#      - manage_dirs
#    volumes:
#      - ./database:/qdrant/storage
#    ports:
#      - "6333:6333"
#      - "6334:6334"
#    networks:
#      - app-network
#
#volumes:
#  postgres_data:
#
#networks:
#  app-network:
#    driver: bridge